apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  generation: 0
  image:
    dockerImageMetadata: null
    metadata: {}
  kind: ImageStreamTag
  lookupPolicy:
    local: false
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
      openshift.io/imported-from: users-db:latest
    labels:
      app: users-db
      app.kubernetes.io/component: users-db
      app.kubernetes.io/instance: users-db
    name: users-db:latest
  tag:
    annotations: null
    from:
      kind: DockerImage
      name: users-db:latest
    generation: null
    importPolicy:
      importMode: Legacy
    name: latest
    referencePolicy:
      type: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    labels:
      app: users-db
      app.kubernetes.io/component: users-db
      app.kubernetes.io/instance: users-db
    name: users-db
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: users-db:latest
    postCommit: {}
    resources: {}
    source:
      contextDir: deployments-strategy/apps/users-db
      git:
        uri: https://github.com/mwambao/DO288-apps
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: mysql-80:latest
      type: Docker
    triggers:
    - github:
        secret: xZln42wpT1TgUjSP37hI
      type: GitHub
    - generic:
        secret: gbVHRPq8UoNacfQMYyXY
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    labels:
      app: users-db
      app.kubernetes.io/component: users-db
      app.kubernetes.io/instance: users-db
    name: users-db
  spec:
    replicas: 1
    selector:
      deploymentconfig: users-db
    strategy:
      type: Recreate
      recreateParams:
        post:
          failurePolicy: Abort
          execNewPod:
            command: ["/post-deploy/import.sh"]
            containerName: users-db
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        labels:
          deploymentconfig: users-db
      spec:
        containers:
        - env:
          - name: MYSQL_DATABASE
            value: users
          - name: MYSQL_PASSWORD
            value: redhat
          - name: MYSQL_USER
            value: developer
          image: users-db:latest
          name: users-db
          ports:
          - containerPort: 3306
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - users-db
        from:
          kind: ImageStreamTag
          name: users-db:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    labels:
      app: users-db
      app.kubernetes.io/component: users-db
      app.kubernetes.io/instance: users-db
    name: users-db
  spec:
    ports:
    - name: 3306-tcp
      port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      deploymentconfig: users-db
  status:
    loadBalancer: {}
kind: List
metadata: {}
